-- MySQL Script generated by MySQL Workbench
-- Tue May 25 11:01:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_name_here
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `role` CHAR(1) NOT NULL DEFAULT 'u',
  `firstname` VARCHAR(255) NULL,
  `lastname` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `ip` VARCHAR(255) NULL,
  `token` VARCHAR(64) NULL DEFAULT NULL,
  `date_logged` DATETIME NULL DEFAULT NULL,
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2;


-- -----------------------------------------------------
-- Table `article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `article` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `image_position` VARCHAR(255) BINARY NULL DEFAULT NULL,
  `sort` INT(4) NOT NULL DEFAULT 9999,
  `is_visible` TINYINT NOT NULL DEFAULT 1,
  `video` VARCHAR(512) NULL,
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_article_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_article_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `article_translation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `article_translation` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `article_id` INT(11) UNSIGNED NOT NULL,
  `locale` CHAR(2) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `perex` TEXT NULL DEFAULT NULL,
  `text` TEXT NULL DEFAULT NULL,
  `slug` VARCHAR(255) NOT NULL,
  INDEX `fk_article_id_idx` (`article_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_article_translation_on_article`
    FOREIGN KEY (`article_id`)
    REFERENCES `article` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `navigation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `navigation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent` INT UNSIGNED NULL,
  `sort` INT NULL DEFAULT 9999,
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_navigation_navigation1_idx` (`parent` ASC),
  INDEX `fk_navigation_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_navigation_navigation1`
    FOREIGN KEY (`parent`)
    REFERENCES `navigation` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_navigation_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `navigation_translation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `navigation_translation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `navigation_id` INT UNSIGNED NOT NULL,
  `locale` CHAR(2) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC),
  INDEX `fk_navigation_translation_navigation1_idx` (`navigation_id` ASC),
  CONSTRAINT `fk_navigation_translation_navigation1`
    FOREIGN KEY (`navigation_id`)
    REFERENCES `navigation` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `file` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sort` INT NULL DEFAULT 9999,
  `source` VARCHAR(512) NOT NULL,
  `thumbnail` VARCHAR(512) NULL,
  `type` CHAR(1) NULL,
  `size` INT NULL,
  `width` INT NULL,
  `height` INT NULL,
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`source` ASC),
  INDEX `fk_file_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_file_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `file_translation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `file_translation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `file_id` INT UNSIGNED NOT NULL,
  `locale` CHAR(2) NOT NULL,
  `title` VARCHAR(512) NULL,
  `description` VARCHAR(1024) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_file_translation_file1_idx` (`file_id` ASC),
  CONSTRAINT `fk_file_translation_file1`
    FOREIGN KEY (`file_id`)
    REFERENCES `file` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `article_has_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `article_has_file` (
  `article_id` INT(11) UNSIGNED NOT NULL,
  `file_id` INT UNSIGNED NOT NULL,
  `sort` INT NULL DEFAULT 9999,
  PRIMARY KEY (`article_id`, `file_id`),
  INDEX `fk_article_has_file_file1_idx` (`file_id` ASC),
  INDEX `fk_article_has_file_article1_idx` (`article_id` ASC),
  CONSTRAINT `fk_article_has_file_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `article` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_has_file_file1`
    FOREIGN KEY (`file_id`)
    REFERENCES `file` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tag` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tag_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tag_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tag_translation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tag_translation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag_id` INT UNSIGNED NOT NULL,
  `locale` CHAR(2) NOT NULL,
  `title` VARCHAR(255) NULL,
  `slug` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tag_translation_tag1_idx` (`tag_id` ASC),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC, `locale` ASC),
  CONSTRAINT `fk_tag_translation_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `article_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `article_has_tag` (
  `article_id` INT(11) UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NOT NULL,
  `sort` INT NULL DEFAULT 999,
  PRIMARY KEY (`article_id`, `tag_id`),
  INDEX `fk_article_has_tag_tag1_idx` (`tag_id` ASC),
  INDEX `fk_article_has_tag_article1_idx` (`article_id` ASC),
  CONSTRAINT `fk_article_has_tag_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `article` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `file_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `file_has_tag` (
  `file_id` INT UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`file_id`, `tag_id`),
  INDEX `fk_file_has_tag_tag1_idx` (`tag_id` ASC),
  INDEX `fk_file_has_tag_file1_idx` (`file_id` ASC),
  CONSTRAINT `fk_file_has_tag_file1`
    FOREIGN KEY (`file_id`)
    REFERENCES `file` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `user`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `user` (`id`, `email`, `role`, `firstname`, `lastname`, `password`, `ip`, `token`, `date_logged`, `date_created`, `date_updated`, `user_id`) VALUES (1, 'info@visualio.cz', 'a', 'Admin', 'Účet', '$2y$10$PuPWZACCJGqG8Z6b472sxuEgbxu2au8TuhMwjWoumO3SdEeb91j4a', '::1', NULL, NULL, DEFAULT, DEFAULT, NULL);

COMMIT;

